#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-systemfonts
Version  : 1.0.1
Release  : 12
URL      : https://cran.r-project.org/src/contrib/systemfonts_1.0.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/systemfonts_1.0.1.tar.gz
Summary  : System Native Font Finding
Group    : Development/Tools
License  : MIT
Requires: R-systemfonts-lib = %{version}-%{release}
Requires: R-cpp11
BuildRequires : R-cpp11
BuildRequires : buildreq-R
BuildRequires : fontconfig-dev
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(freetype2)

%description
handling varies between systems it is difficult to correctly locate 
    installed fonts across different operating systems. The 'systemfonts' 
    package provides bindings to the native libraries on Windows, macOS and 
    Linux for finding font files that can then be used further by e.g. graphic
    devices. The main use is intended to be from compiled code but 'systemfonts'
    also provides access from R.

%package lib
Summary: lib components for the R-systemfonts package.
Group: Libraries

%description lib
lib components for the R-systemfonts package.


%prep
%setup -q -c -n systemfonts
cd %{_builddir}/systemfonts

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1612888577

%install
export SOURCE_DATE_EPOCH=1612888577
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library systemfonts
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library systemfonts
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library systemfonts
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc systemfonts || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/systemfonts/DESCRIPTION
/usr/lib64/R/library/systemfonts/INDEX
/usr/lib64/R/library/systemfonts/LICENSE
/usr/lib64/R/library/systemfonts/Meta/Rd.rds
/usr/lib64/R/library/systemfonts/Meta/features.rds
/usr/lib64/R/library/systemfonts/Meta/hsearch.rds
/usr/lib64/R/library/systemfonts/Meta/links.rds
/usr/lib64/R/library/systemfonts/Meta/nsInfo.rds
/usr/lib64/R/library/systemfonts/Meta/package.rds
/usr/lib64/R/library/systemfonts/Meta/vignette.rds
/usr/lib64/R/library/systemfonts/NAMESPACE
/usr/lib64/R/library/systemfonts/NEWS.md
/usr/lib64/R/library/systemfonts/R/sysdata.rdb
/usr/lib64/R/library/systemfonts/R/sysdata.rdx
/usr/lib64/R/library/systemfonts/R/systemfonts
/usr/lib64/R/library/systemfonts/R/systemfonts.rdb
/usr/lib64/R/library/systemfonts/R/systemfonts.rdx
/usr/lib64/R/library/systemfonts/doc/c_interface.R
/usr/lib64/R/library/systemfonts/doc/c_interface.Rmd
/usr/lib64/R/library/systemfonts/doc/c_interface.html
/usr/lib64/R/library/systemfonts/doc/index.html
/usr/lib64/R/library/systemfonts/help/AnIndex
/usr/lib64/R/library/systemfonts/help/aliases.rds
/usr/lib64/R/library/systemfonts/help/paths.rds
/usr/lib64/R/library/systemfonts/help/systemfonts.rdb
/usr/lib64/R/library/systemfonts/help/systemfonts.rdx
/usr/lib64/R/library/systemfonts/html/00Index.html
/usr/lib64/R/library/systemfonts/html/R.css
/usr/lib64/R/library/systemfonts/include/systemfonts-ft.h
/usr/lib64/R/library/systemfonts/include/systemfonts.h
/usr/lib64/R/library/systemfonts/tests/testthat.R
/usr/lib64/R/library/systemfonts/tests/testthat/test-match_font.R
/usr/lib64/R/library/systemfonts/tests/testthat/test-system_fonts.R
/usr/lib64/R/library/systemfonts/unfont.ttf

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/systemfonts/libs/systemfonts.so
